### ISSUE TITLE
transferFrom 和transfer方法是否需要合并优化

### ISSUE THREAD

**Issue by heyulong** [Alchemint/alchemintToken#10]
https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L346-L386

![image](https://user-images.githubusercontent.com/12603745/41695125-37b98738-7540-11e8-8f18-56573d4bb253.png)

**Comment by alchemintadmin** [comment]
由于Nep-5标准已经将Approve以及transferFrom功能去除，因此transfer方法将不会包含transferFrom的特性，这两个方法我们会分开.
