### ISSUE TITLE
Bounty: parameter length checks need to be performed inside each method

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#11]
Changes needed here: 
https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L173
https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L194
https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L236
https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L288

These are required because the NEO Distributed Exchange documentation states that methods can be also be invoked using `invokefunction`/RPC bypassing the `Main()` entrypoint.

Reference: http://docs.neo.org/en-us/exchange/v2.7.4.html#dealing-with-nep-5-assets-transactions

**Comment by alchemintadmin** [comment]
Invokefunction/RPC bypassing the Main() entrypoint is not supported by present version of Neo. If the coming version do that, we will launch a upgrade version of SDT.

**Comment by mwherman2000** [comment]
There was very long, messy discussion about an NEP-5 Amendment PR that was accepted today.  
https://github.com/neo-project/proposals/pull/44#issuecomment-399313488

The net of the decision was to leave NEP-5 as vague and misleading from a SC implementors perspective.  I wish you the best of luck guys.
