### ISSUE TITLE
Bounty: `setTxInfo()` needs to be a public method to be callable from `invokemethod`/RPC

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#12]
Reference: https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L236

General reference: <http://docs.neo.org/en-us/exchange/v2.7.4.html#dealing-with-nep-5-assets-transactions>

**Comment by alchemintadmin** [comment]
Invokefunction/RPC bypassing the Main() entrypoint is not supported by present version of Neo. If the coming version do that, we will launch a upgrade version of SDT.

**Comment by mwherman2000** [comment]
There was very long, messy discussion about an NEP-5 Amendment PR that was accepted today.  
https://github.com/neo-project/proposals/pull/44#issuecomment-399313488

The net of the decision was to leave NEP-5 as vague and misleading from a SC implementors perspective.  I wish you the best of luck guys.
