### ISSUE TITLE
所有暴露在接口层的storage的key都要加一个tag

### ISSUE THREAD

**Issue by wowoyinwei** [Alchemint/alchemintToken#2]
https://neo.org/blog/details/3081

**Comment by alchemintadmin** [comment]
已经对地址的位数进行了校验，因此无法对已有的key进行注入攻击。但增加前缀是更安全的做法，因此我们会进行优化。
这个issue被认作一个优化，将可以得到$300等值的SDT奖励。
请作者将邮箱地址和NEO地址发送到bug@alchemint.io
