### ISSUE TITLE
Bounty: Your token SC is not NEP-10 complaint

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#4]
NEP-10: https://github.com/neo-project/proposals/blob/master/nep-10.mediawiki

1. You need to ensure all of your SC's **required** operations and methods are defined in an NEP (or NCP).
NOTE: With the final acceptance of NEP-10, all of the optional methods in NEP-5 were removed from the specification: https://github.com/neo-project/proposals/issues/40#issuecomment-388699187
Latest version of the NEP-5 spec: <https://github.com/neo-project/proposals/blob/master/nep-5.mediawiki>

2. Create new NEPs (or NCPs) for your SC's required methods that are not in NEP-5

3. You need to implement the `supportedStandards()` operation/method in your SC. Here's an example:
https://github.com/neo-project/proposals/issues/40#issuecomment-385080365

My NEO wallet address: AXkGHLyg6qrFvEKzpoQN5x7Af4HKEkm5Tt

**Comment by alchemintadmin** [comment]
We choose NEP-5 as SDT token standard. We consider that NEP-10 is uncompleted at present, so we are not going to implement the standard of NEP-10 at this version.

**Comment by mwherman2000** [comment]
NEP-10 is an Accepted and Final NEO standard:

![image](https://user-images.githubusercontent.com/6101736/41718450-ff703b34-752a-11e8-8987-4bd1d1470273.png)

Reference: https://github.com/neo-project/proposals/blob/master/nep-10.mediawiki

It will be very expensive to have to pay to redeploy at a later date. GAS will never be cheaper than it is now. I'm trying to save you the costs of an extra mainnet SC deployment.

Will you still pay a Bounty when you do make the change and have to redeploy?
