### ISSUE TITLE
Bounty: `Decimals()`, `Name()`, `Symbol()`, `TotalSupply()`, and `Name()` are not NEP-5 compliant

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#5]
These NEP-5 methods need to start with a lower-case letter: https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L48

NEP-5 methods: https://github.com/neo-project/proposals/blob/master/nep-5.mediawiki#methods

My NEO wallet address: AXkGHLyg6qrFvEKzpoQN5x7Af4HKEkm5Tt

**Comment by alchemintadmin** [comment]
We will follow this recommend. This issue is comfirmed as a optimizing. The author will receive $300 worth SDT as reward.

**Comment by mwherman2000** [comment]
It's more than a recommendation.  The method names are required to have a leading lowercase letter.  Reference: <http://docs.neo.org/en-us/exchange/v2.7.4.html#dealing-with-nep-5-assets-transactions>

**Comment by mwherman2000** [comment]
The ICO template is a horrible mess ...not complaint with any NEP.  Reference: https://github.com/neo-project/proposals/pull/44#issuecomment-390194827

**Comment by mwherman2000** [comment]
In addition, the NEP-5 landscape has changed significantly in the last 6 hours as I work with @Eerikzhang to get NEP-5 wording clarified.  

Read the following discussion starting here: https://github.com/neo-project/proposals/pull/44#issuecomment-399313488
