### ISSUE TITLE
Bounty: No address length checks and `var keyFrom = new byte[] { 0x11 }.Concat(from);`

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#6]
1. Using a simple single byte prefix for your NEO storage keys isn't a safe pattern to use when the rest of the key is also an array of bytes passed in as a parameter.  You might get away with it in your specific scenario but more generally I can start to spoof your code by providing addresses that are one byte shorter than expected.

https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L92

2. Related to the above (and more importantly), you code doesn't validate the length of incoming address parameters.

My NEO wallet address: AXkGHLyg6qrFvEKzpoQN5x7Af4HKEkm5Tt

**Comment by alchemintadmin** [comment]
The previous version code has validated the length of incoming address parameters. And at this version, we add prefix as a optimizing.
```c
public static bool transferFrom(byte[] owner, byte[] spender, byte[] to,BigInteger amount)
        {
            if (owner.Length != 20 || spender.Length != 20 || to.Length != 20) return false;
 if (operation == "transfer")
                {
                    if (args.Length != 3) return false;
                    byte[] from = (byte[])args[0];
                    byte[] to = (byte[])args[1];
                    if (from.Length != 20 || to.Length != 20)
                        return false;
```
