### ISSUE TITLE
Bounty: Your SC implements several methods that are not defined in an accepted NEP

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#7]
- `init` and `Init()`  (also a potential issue with `Init()` starting with a capital letter)
- `transfer_contract` and no corresponding invokable method
- `allowance` and `Allowance()`
- `approve` and `Approve()`
- `transferFrom` and `TransferFrom()`
- `getTXInfo` and `GetTXInfo()`

My NEO wallet address: AXkGHLyg6qrFvEKzpoQN5x7Af4HKEkm5Tt

**Comment by alchemintadmin** [comment]
The issue of lowcase is same as [issue5](https://github.com/Alchemint/alchemintToken/issues/5).
The standard don't required that a interface must correspond to a unique method.

**Comment by mwherman2000** [comment]
You should then either submit it as a new NEP or create an NCP (NEO Community Proposal) for these operations and methods ...so that you can be issued an NEP code or NCP code to used with NEP-10.

NCPs are discussed here (and approved by Erik): https://github.com/neo-project/proposals/issues/47#issuecomment-397849941

**Comment by mwherman2000** [comment]
RE: The standard don't required that a interface must correspond to a unique method.

Which standard are you referring to?
