### ISSUE TITLE
Bounty: `approve` / `Approve` event implemented but not defined in an accepted NEP

### ISSUE THREAD

**Issue by mwherman2000** [Alchemint/alchemintToken#8]
https://github.com/Alchemint/alchemintToken/blob/master/alchemintToken/SDTToken.cs#L17

My NEO wallet address: AXkGHLyg6qrFvEKzpoQN5x7Af4HKEkm5Tt

**Comment by alchemintadmin** [comment]
Our scenario need Approve event.

**Comment by mwherman2000** [comment]
You should then either submit it as a new NEP or create an NCP (NEO Community Proposal) for you `Approve` event ...so that you can be issued an NEP code or NCP code to used with NEP-10.

NCPs are discussed here (and approved by Erik): https://github.com/neo-project/proposals/issues/47#issuecomment-397849941
