### ISSUE TITLE
A small tip

### ISSUE THREAD

**Issue by Liaojinghui** [Alchemint/alchemintToken#9]
In the function <transfer> line 90, you checked the length of "from", however, even from is empty, you still have to call  [setTxInfo(from, to, value); Transferred(from, to, value);], which i believe is unnecessary.

    //付款方
            if (from.Length > 0)
            {
                var keyFrom = new byte[] { 0x11 }.Concat(from);
                BigInteger from_value = Storage.Get(Storage.CurrentContext, keyFrom).AsBigInteger();
                if (from_value < value) return false;
                if (from_value == value)
                    Storage.Delete(Storage.CurrentContext, keyFrom);
                else
                    Storage.Put(Storage.CurrentContext, keyFrom, from_value - value);
            }
            //收款方
            if (to.Length > 0)
            {
                var keyTo = new byte[] { 0x11 }.Concat(to);
                BigInteger to_value = Storage.Get(Storage.CurrentContext, keyTo).AsBigInteger();
                Storage.Put(Storage.CurrentContext, keyTo, to_value + value);
            }
            // Even from or to is empty, it still comes here

            //记录交易信息
            setTxInfo(from, to, value);
            //notify
            Transferred(from, to, value);
            return true;
        }

**Comment by alchemintadmin** [comment]
Same as [issue1](https://github.com/Alchemint/alchemintToken/issues/1).
